### ISSUE TITLE
Checkbox UI 개선

### ISSUE THREAD

**Issue by tTab1204** [six-sense/jaranda#77]
## 설명
`AdminPage`의 Checkbox UI 개선

## 할 일
- [x] checkbox 크기 늘리기
- [x] checkbox 색 변경
- [x] checkbox 클릭 시 animation 추가

## 일정
2021.08.04

### 추가
`AdminPage`에서 직접 작업하면 겹치니 따로 test파일을 하나 만들어서 진행하겠습니다!

**Comment by yh1120** [comment]
제가 계정별 Pages checkbox 클릭상태 구현하도록 하겠습니다.
